stages:
  - build
  - deploy

build-django:
  stage: build
  script:
    - echo "123"
    - docker build -t ca .
  tags:
    - docker_build
    - example

deploy-django:
  stage: deploy
  image: docker:latest
  services:
    - docker:dind
  script:
    - echo "Deploying Backend..."
    - echo "Backend Deployment Complete!"
  tags:
    - docker_deploy
    - example