stages:
  - build
  - deploy

build-django:
  stage: build
  image: docker:latest
  script:
    - echo "123"
    - hostname
    - ps aux
  tags:
    - example

deploy-django:
  stage: deploy
  image: docker:latest
  services:
    - docker:dind
  script:
    - echo "Deploying Backend..."
    - echo "Backend Deployment Complete!"
  tags:
    - example