stages:
  - build
  - deploy

build-django:
  stage: build
  script:
    - echo "123"
    - docker build -t ca .
  tags:
    - echo "Build Backend..."
    - docker_build
    - example

deploy-django:
  stage: deploy
  image: docker:latest
  services:
    - docker:dind
  script:
    - echo "Deploying Backend..."
    - docker run -p 9000:9000 --name ca ca "/bin/bash -c python manager.py
    - echo "Backend Deployment Complete!"
  tags:
    - docker_build
    - example