version: '3'

services:
  db:
    container_name: db
    image: mysql:5.7
    network_mode: host
    environment:
       MYSQL_DATABASE: 'pets'
       MYSQL_USER: 'test'
       MYSQL_PASSWORD: 'test'
       MYSQL_ROOT_PASSWORD: '123123'
  redis:
    container_name: redis
    image: redis:5.0.5
    network_mode: host
  django:
    container_name: django
    image: ca:latest
    network_mode: host
